name: divine_pos
description: "Divine POS â€” A professional Point-of-Sale Flutter application."
publish_to: "none"

version: 1.0.0+1

# environment:
#   sdk: ^3.9.2
#   flutter: ">=3.24.0"

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.0
  package_info_plus: ^8.0.0
  upgrader: 12.3.0

  flutter_staggered_grid_view: ^0.7.0

  # syncfusion_flutter_sliders: ^25.1.37
  # syncfusion_flutter_core: ^25.1.37
  flutter_xlider: ^3.5.0

  # ------------ CORE LIBRARIES ------------
  intl: ^0.20.2 # date, number formatting
  dio: ^5.4.3 # API client
  flutter_dotenv: ^6.0.0 # .env config

  # ------------ STATE MANAGEMENT & ROUTER ------------
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0

  # ------------ LOCAL STORAGE ------------
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # ------------ UI PACKAGES ------------
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1 # optional: improves UI typography
  flutter_svg: ^2.0.10+1 # SVG logos/icons
  cached_network_image: ^3.4.1 # caching for product images

  # ------------ UTILITIES ------------
  uuid: ^4.5.0 # useful for generating IDs
  connectivity_plus: ^6.1.0 # network status
  shared_preferences: ^2.3.2 # lightweight preferences

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sms_autofill: ^2.3.0

flutter:
  uses-material-design: true

  fonts:
    - family: Ballpoint Rush
      fonts:
        - asset: assets/fonts/Ballpoint Rush/BallpointRushDEMO.otf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700

    - family: Rushter Glory
      fonts:
        - asset: assets/fonts/Rushter Glory/Rushter Glory.ttf

  assets:
    - assets/Login/
    - assets/dashboard/banner/
    # - assets/dashboard/action_section/
    - assets/dashboard/categories/
    - assets/dashboard/collection/
    - assets/dashboard/banner/hero_banner.png
    - assets/dashboard/action_section/catalouge.png
    - assets/dashboard/action_section/feedback-form.png
    - assets/dashboard/action_section/know_your_diamond_value.png
    - assets/dashboard/action_section/verify-track.png
    - assets/dashboard/action_section/scan-ready-product.jpg
    - assets/dashboard/action_section/right-arrow-icon.png
    - assets/jewellery/filters/
    - assets/jewellery/filters/metal/
    # filter tag jewellery listing
    - assets/jewellery/filter_tags/
    - assets/jewellery/
    # - assets/images/
    # - assets/config/
    # - .env

    - assets/icons/
